name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: install cmake
      run: choco install cmake
    - name: generate cmake
      run: cmake . -G "Visual Studio 17 2022" -DOPENSSL_ROOT_DIR="./bin/windows"
    - name: cmake build
      run: cmake --build . --config Release
